---
name: Build ChkTeX
"on":
  pull_request:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        build_target: ["full", "slim"]
        arch: ["arm64", "amd64"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: "./scripts/build ${{ matrix.build_target }} ${{ matrix.arch }}"
      - run: "./scripts/test $VERSION_TAG"
      - run: "docker save $LATEST_TAG $VERSION_TAG --output chktex-${{ matrix.build_target }}-${{ matrix.arch }}.tar"  # yamllint disable-line rule:line-length
      - uses: actions/upload-artifact@v3
        with:
          name: "chktex-${{ matrix.build_target }}-${{ matrix.arch }}.tar"
          path: "chktex-${{ matrix.build_target }}-${{ matrix.arch }}.tar"

  push:
    if: github.ref_name == 'main'
    needs:
      - build-and-test
    strategy:
      fail-fast: false
      matrix:
        build_target: ["full", "slim"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - run: "docker load --input ./chktex-${{ matrix.build_target }}-arm64.tar/chktex-${{ matrix.build_target }}-arm64.tar"  # yamllint disable-line rule:line-length
      - run: "docker load --input ./chktex-${{ matrix.build_target }}-amd64.tar/chktex-${{ matrix.build_target }}-amd64.tar"  # yamllint disable-line rule:line-length
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: "./scripts/push ${{ matrix.build_target }}"
      - run: "./scripts/create-manifest ${{ matrix.build_target }}"
